name: learn-github-actions
on: [push]
jobs:
  check-pandas-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.6", "3.8", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
        env:
          DUMMY_ENV: hellothere
      - name: Install dependencies
        run: pip install pandas
      - run: python -c "import pandas; print(pandas.__version__)"
      - name: Run build script
        run: ./.github/scripts/build.sh
        shell: bash
      - name: Create log file
        run: expr 1 + 1 > output.log
      - name: Upload to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: output-log-file
          needs: check-pandas-version (3.10)
